version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - govet
    - grouper
    - ineffassign
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - tparallel
    - unconvert
    - unused
    - usetesting
  exclusions:
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - deadcode
          - govet
          - unparam
          - unused
        path: lntest/itest/.*
      - path: lntest/
        text: lostcancel
issues:
  new-from-rev: 01f696afce2f9c0d4ed854edefa3846891d01d8a
formatters:
  enable:
    - gofmt
    - goimports
