name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.18, 1.19]
    steps:
      - name: Set up Go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a #v3.2.1
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0"
      - name: Build
        run: go build ./...
      - name: Lint
        run: |
          golangci-lint run --disable-all --deadline=10m --skip-files="mobile\\/.*generated\\.go" --enable=gofmt --enable=vet --enable=gosimple --enable=unconvert --enable=ineffassign --enable=unused

      - name: Package test binaries
        run: |
          export GOPATH=$(go env GOPATH)
          make package-test-binaries

      - name: Upload test binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.go }}-test-binaries
          path: dcrlnd_testbins.tar.gz

  testsuite:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.18]
        testsuite:
          - unit-race # unit tests
          - itest-only # embedded wallet using dcrd for sync and chain ops
          - itest-only walletimpl=embeddedwallet_dcrw # embedded wallet, dcrd sync but dcrw chain ops
          - itest-only walletimpl=embeddedwallet_dcrw backend=spv # embedded wallet, spv sync and dcrw chain ops
          - itest-only walletimpl=remotewallet # remote wallet dcrd sync
          - itest-only walletimpl=remotewallet backend=spv # remote wallet spv sync
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out source
        uses: actions/checkout@v1

      - name: Download the test binaries
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.go }}-test-binaries

      - name: Unpack the test binaries
        run: |
          export GOPATH=$(go env GOPATH)
          mv ${{ matrix.go }}-test-binaries/* .
          make unpack-test-binaries

      - name: Run the test suite
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=${PATH}:$(go env GOPATH)/bin
          make ${{ matrix.testsuite }}

      - name: Compress log files
        if: always()
        run: |
          find . -iname *.log | tar -T - --ignore-failed-read -czf output-logs.tar.gz

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.go }}-${{ matrix.testsuite }}-logs.tar.gz
          path: output-logs.tar.gz


